# Generated by Django 4.1.7 on 2023-03-05 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DataType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "aggregation_type",
                    models.CharField(
                        choices=[
                            ("COUNT", "Conteo"),
                            ("SUM", "Suma"),
                            ("PRODUCT", "Producto"),
                            ("AVERAGE", "Promedio"),
                            ("LAST_VALUE", "Ultimo Valor"),
                            ("LAST_RESULT", "Ultimo Resultado"),
                            ("CONSTANT", "1"),
                        ],
                        default="COUNT",
                        max_length=16,
                    ),
                ),
                (
                    "value_type",
                    models.CharField(
                        choices=[
                            ("MONEY", "Unidades Monetarias"),
                            ("HOURS", "Horas"),
                            ("EVENTS", "Eventos"),
                            ("UNITS", "Unidades"),
                            ("PERCENTAGE", "Porcentaje"),
                        ],
                        default="UNITS",
                        max_length=16,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Indicator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("details", models.CharField(max_length=255)),
                (
                    "desired_tendency",
                    models.CharField(
                        choices=[
                            (">", "Creciente"),
                            ("=", "Ninguna"),
                            ("<", "Decreciente"),
                        ],
                        default="=",
                        max_length=1,
                    ),
                ),
                (
                    "denominator",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="sistema_indicadores.datatype",
                    ),
                ),
                (
                    "department",
                    models.ManyToManyField(to="sistema_indicadores.department"),
                ),
                (
                    "numerator",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="sistema_indicadores.datatype",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="department",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="sistema_indicadores.organization",
            ),
        ),
        migrations.CreateModel(
            name="DataPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.IntegerField()),
                ("date", models.DateField()),
                (
                    "data_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sistema_indicadores.datatype",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sistema_indicadores.department",
                    ),
                ),
            ],
        ),
    ]
